### ISSUE TITLE
Preferred Applications - Thunderbird Doesn't Appear

### ISSUE THREAD

**Issue by Geyup** [CinnamonSlackBuilds/csb#10]
I'm running Slackware 14.2 x86_64

Under the Preferred Applications > Mail Thunderbird I assumed, would appear by default, if I'm not mistaken it does in Mint.

Then I click the drop down to add it in, and Thunderbird doesn't even appear in the list.

Hmm

**Comment by willysr** [comment]
Hi geyup

I asked Clem about this before and it seems that it must be set manually. 
I looked around and found this: https://kevinlocke.name/bits/2012/07/18/thunderbird-default-browser-linux/

can you try this?
`xdg-mime default firefox.desktop x-scheme-handler/http`

**Comment by Geyup** [comment]
Not using Cinnamon anymore, not stable, not even stable in Mint...

**Comment by willysr** [comment]
i have been using it in my office and it works fine here
It does require more resources compared to MATE but if your hardware is modern enough, it should be running smoothly

**Comment by Skaendo** [comment]
Cinnamon is running good on my test rig here as well. And I'm running on a stripped down Slackware base. On top of that, it's a Dell Inspiron 1520 from '07. 2 GHz w/4 GB RAM

**Comment by willysr** [comment]
I'm using HP Pro i3 CPU 540 @ 3.07GHz with 8 GB RAM at the office while i'm using Dual Core with 4 GB RAM at home and both are running both MATE and Cinnamon (depends on mood)
