### ISSUE TITLE
slackware 14.2 binary package out of date.

### ISSUE THREAD

**Issue by nnnewb** [CinnamonSlackBuilds/csb#11]
I used slackpkg+ install csb binary packages
```
slackpkg install csb
xwmconfig
```
after install, i have try `startx` and failed. error message looks not found libicule.so.51, but it's /usr/lib64/libicule.so.56.
dose binary package out of date?

**Comment by willysr** [comment]
Did you point it to the correct repository location?
i built all binary packages on a clean Slackware 14.2 VM so it should be pointing to correct library

**Comment by nnnewb** [comment]
I had add this line in `/etc/slackpkg/slackpkgplus.conf`
```
MIRRORPLUS['csb']=http://slackware.uk/csb/
```
is it correct?

**Comment by willysr** [comment]
No, it should point to the correct directory such as http://slackware.uk/csb/14.2/x86_64/

**Comment by nnnewb** [comment]
it's work!
thank you for your help!
