### ISSUE TITLE
3.2-prep: incorrect order in build script

### ISSUE THREAD

**Issue by thegreyshadow** [CinnamonSlackBuilds/csb#12]
In the script ./build-cinammon.sh:

building gnome-common fails because it requires libgnomekbdui.

workaround: building libgnomekbd prior to gnome-common seems to allow building to proceed.

*edit*: Looks like it's xapps the software requiring libgnomekbdui.

Thanks,

Eduardo

**Comment by willysr** [comment]
Closed in e10e76e62e525eff92297cfc43e659ee4f3ed835

**Comment by thegreyshadow** [comment]
Thank you!!
