### ISSUE TITLE
Issue with screen unlocking

### ISSUE THREAD

**Issue by realChytraeus** [CinnamonSlackBuilds/csb#13]
I'm using the 14.2 branch. I am building the packages myself, not using packages from the repo. I have screen unlocking issues after upgrading cinnamon to 3.2.7 and cinnamon-screensaver to 3.2.12. The fundamental issue is that after the screen locks, I reopen my laptop lid or move the mouse to prompt for the place to enter my password and username. However, there aren't any boxes to enter these credentials. My workaround is to do ctrl-alt-backspace and then restart x11.
I've since downgrade cinnamon to 3.2.6 and cinnamon-screensaver to 3.2.10 and the issue has resolved.

**Comment by willysr** [comment]
Should be fixed by 9e8b6209e0e406158e78ffcef39616b128990502 in master and f7197dc11613874f485db6fa9a9fcb43e3ff724f in 14.2 branch

please confirm

**Comment by realChytraeus** [comment]
Yes this fixes the problem.
