### ISSUE TITLE
Missing a few useful apps

### ISSUE THREAD

**Issue by tbazant** [CinnamonSlackBuilds/csb#14]
Hi!
I really like running the cinnamon desktop on top of my SLack 14.2
What I'm missing are a few useful applications  - such as gedit, gnome-terminal, evince, cheese...that are part of GNOME itself. Do you plan to include/provide them as well? I've found theyr included in https://github.com/slackport/gfs. Unfortunately, GFS dont provide binary packages and compiling takes ages on my old computer.
Thanks!

Tomas

**Comment by willysr** [comment]
Hi @tbazant, i'm focusing on the Cinnamon desktop, not the whole GNOME-based desktop.

Most of the GNOME-based apps can be built via SlackBuilds repository.

I'm closing this issue.
