### ISSUE TITLE
14.2/cinnamon-desktop-3.4.0 needs gdk-pixbuf-2.0

### ISSUE THREAD

**Issue by Skaendo** [CinnamonSlackBuilds/csb#18]
make  all-recursive
make[1]: Entering directory '/tmp/lmse-3.4/cinnamon-desktop-3.4.0'
Making all in libcinnamon-desktop
make[2]: Entering directory '/tmp/lmse-3.4/cinnamon-desktop-3.4.0/libcinnamon-desktop'
  CC       gnome-thumbnail-pixbuf-utils.lo
  CC       gnome-desktop-utils.lo
  CC       gnome-desktop-thumbnail.lo
In file included from gnome-desktop-thumbnail.c:42:0:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:30:42: fatal error: gdk-pixbuf/gdk-pixbuf-macros.h: No such file or directory
compilation terminated.
Makefile:762: recipe for target 'gnome-desktop-thumbnail.lo' failed
make[2]: *** [gnome-desktop-thumbnail.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from gnome-desktop-thumbnail.h:36:0,
                 from gnome-thumbnail-pixbuf-utils.c:33:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:30:42: fatal error: gdk-pixbuf/gdk-pixbuf-macros.h: No such file or directory
compilation terminated.
In file included from /usr/include/gtk-3.0/gdk/gdkpixbuf.h:33:0,
                 from /usr/include/gtk-3.0/gdk/gdkcairo.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:33,
                 from gnome-desktop-utils.h:37,
                 from gnome-desktop-utils.c:32:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:30:42: fatal error: gdk-pixbuf/gdk-pixbuf-macros.h: No such file or directory
compilation terminated.
Makefile:762: recipe for target 'gnome-thumbnail-pixbuf-utils.lo' failed
make[2]: *** [gnome-thumbnail-pixbuf-utils.lo] Error 1
Makefile:762: recipe for target 'gnome-desktop-utils.lo' failed
make[2]: *** [gnome-desktop-utils.lo] Error 1
make[2]: Leaving directory '/tmp/lmse-3.4/cinnamon-desktop-3.4.0/libcinnamon-desktop'
Makefile:484: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/lmse-3.4/cinnamon-desktop-3.4.0'
Makefile:416: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Skaendo** [comment]
cogl wants gdk-pixbuf-2.0 as well.

**Comment by willysr** [comment]
do you have gdk-pixbuf2 ?
it's already part of Slackware 14.2

**Comment by willysr** [comment]
It contains the files you needed
```
usr/include/gdk-pixbuf-2.0/
usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/
usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/gdk-pixbuf-xlib.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf-xlib/gdk-pixbuf-xlibrgb.h                                                                                                                     
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/                                                                                                                                              
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-autocleanups.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-enum-types.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-features.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-io.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-loader.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-macros.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-marshal.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-simple-anim.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-transform.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h
usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h
```

**Comment by Skaendo** [comment]
Unless something strange happened, I am running a standard Slackware64-14.2 install. I suppose that I'm going to do a reinstall and reset my build rig. At least there isn't too much on it and a rebuild will be fairly quick.

**Comment by willysr** [comment]
i also perform the compilation on the same VM that i used to build 3.2 packages, so nothing changes there except for -stable updates from Slackware and Cinnamon.

**Comment by willysr** [comment]
my suggestion will be reinstalling gdk-pixbuf2 and see if that solves your problem

**Comment by Skaendo** [comment]
Will do. Thanks.

**Comment by Skaendo** [comment]
Yes, that fixed it. But now I'm concerned what happened. I'm going to slap a new drive in my build rig and reset.

Sorry to bother ya.
