### ISSUE TITLE
.la files question

### ISSUE THREAD

**Issue by Skaendo** [CinnamonSlackBuilds/csb#26]
### Slackware Version
64-current

### Cinnamon Version
3.6.7

### GIT Branch
master

### Description
I don't know if this is an issue or not, maybe just some clarification.
I was to understand that there is not supposed to be any .la files under /usr/lib and /usr/lib64, correct?

Well I noticed that you added the command to the build scripts to remove them, but cinnamon and cinnamon-settings-daemon have .la files in /usr/lib${LIBDIRSUFFIX}/$PRGNAM. Should these be removed as well? 

Should there actually be any .la files under /usr/lib${LIBDIRSUFFIX}?

**Comment by willysr** [comment]
No, they are needed for plugins. You can try to move them and see if plugins are still working or not

**Comment by Skaendo** [comment]
I see, thanks. I did a little comparing and I believe that they are needed for linking to other libs.
