### ISSUE TITLE
libgksu error

### ISSUE THREAD

**Issue by Skaendo** [CinnamonSlackBuilds/csb#27]
### Slackware Version
64-current
### Cinnamon Version
3.6.7
### GIT Branch
master
### Description
I just came across a issue building libgksu on a fresh clean install of -current.
I don't know if it makes a difference but I'm building with slackrepo.
What happened is that it would error out with the message "libX11.so.6: error adding symbols: DSO missing from command line".

I fixed it by adding '-lX11' to the SLKCFLAGS

Sorry that I keep bothering you....

**Comment by willysr** [comment]
It has been merged as in 094e35201ebad940ce09a2c0ccc8702002962e39
