### ISSUE TITLE
Caribou is failing

### ISSUE THREAD

**Issue by xexpanderx** [CinnamonSlackBuilds/csb#29]
### Slackware Version
14.2 64-bit + multilib
### GIT Branch
14.2
### Description

```
Traceback (most recent call last):
  File "../tools/make_schema.py", line 3, in <module>
    from gi.repository import GLib
ImportError: No module named gi.repository
Makefile:846: recipe for target 'org.gnome.caribou.gschema.xml.in' failed
make[2]: *** [org.gnome.caribou.gschema.xml.in] Error 1
make[2]: Leaving directory '/tmp/csb/caribou-0.4.21/data'
Makefile:519: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/csb/caribou-0.4.21/data'
Makefile:474: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
bash-4.3# exit

```

**Comment by xexpanderx** [comment]
I tryed importing gi.repository in python 3:

`python3`

and then:
`
import gi.repository`

It works, python3 finds this module. Im pretty much lost now...

**Comment by willysr** [comment]
hi @xexpanderx 

Which branch did you use to build this package?
Also, do you have full installation of Slackware 14.2?
I tested them on a full installation

**Comment by xexpanderx** [comment]
I use 14.2 branch. I have full installation of Slackware 14.2.

**Comment by xexpanderx** [comment]
I removed the multilib, still same error. I have no idea how to tackle this.

**Comment by xexpanderx** [comment]
Ok, it works if installing manually:
```

./configure --prefix=/usr
make
trackinstall make install
```

**Comment by willysr** [comment]
If it works by installing it manually, it should also work with the SlackBuild as it doesn't have any special options

**Comment by xexpanderx** [comment]
Thanks, you can close this issue. I have no idea what happened, running it again worked. 

Thank you for your hard work.
