### ISSUE TITLE
mint-y-theme and cinnamon-themes

### ISSUE THREAD

**Issue by skaendo** [CinnamonSlackBuilds/csb#31]
Hey Willy,

Just a heads-up, mint-y-theme and cinnamon-themes are depreciated, archived and/or no longer maintained. The package that replaces them is mint-themes: https://github.com/linuxmint/mint-themes . I'm not sure if this affects the 3.8.x branch of Cinnamon or only 4.x.

Ed

**Comment by willysr** [comment]
Thanks for the heads-up.
Unfortunately, they haven't released any tarball so i will wait until they do so.

**Comment by skaendo** [comment]
They haven't tagged any here on github (I hate it when they do this), but they do have source tarballs in their main repo.

http://packages.linuxmint.com/pool/main/m/mint-themes/
