### ISSUE TITLE
Desktop crashes when moving panel from bottom of screen to the top of the screen.

### ISSUE THREAD

**Issue by realChytraeus** [CinnamonSlackBuilds/csb#32]
### Slackware Version
64-current
### Cinnamon Version
4
### GIT Branch
cinnamon4
### Description
everything built fine on a clean, full install of slackware64-current on a Lenovo T420s with 8 gigs of RAM.
I have one issue where after starting the desktop, I click the bottom panel, choose 'modify panel' and then 'move panel'. When I proceed to move the panel to the top, Cinnamon crashes and/or falls into fallback mode. I then click 'restart' to restart the desktop, and all is well.

**Comment by willysr** [comment]
Hi @realChytraeus 

can you give a try on Cinnamon 4.0.1 ?
It has some fixes regarding the panels
https://github.com/linuxmint/Cinnamon/commit/4524526b10bcbab4939c21693a6e0fd52bb69c91

**Comment by realChytraeus** [comment]
Yes, I can. I upgraded tonight. No more problems with the panel. One other issue I had was during the downloading of one of the files, cinnamon-control-center 4.0.1 was not available but 4.0.0 was so I used that.

**Comment by willysr** [comment]
c-c-c is now upgraded to 4.0.1

**Comment by willysr** [comment]
i bumped some other components as well. Please check the cinnamon4 branch

**Comment by realChytraeus** [comment]
c-c-c 4.0.1 code will not download for me.
`bash-4.4$ sudo ./cinnamon-control-center.SlackBuild
--2018-11-14 16:31:41--  https://github.com/linuxmint/cinnamon-control-center/archive/4.0.1/cinnamon-control-center-4.0.1.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/linuxmint/cinnamon-control-center/tar.gz/4.0.1/cinnamon-control-center-4.0.1 [following]
--2018-11-14 16:31:41--  https://codeload.github.com/linuxmint/cinnamon-control-center/tar.gz/4.0.1/cinnamon-control-center-4.0.1
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-14 16:31:41 ERROR 404: Not Found.

tar: /home/chytraeus/csb/cinnamon-control-center/cinnamon-control-center-4.0.1.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
`

**Comment by willysr** [comment]
Sorry, i made a mistake
it supposed to be cinnamon-settings-daemon, not cinnamon-control-center

**Comment by willysr** [comment]
you need to reset the branch from master again as i deleted the wrong commit and put a new commit on top to update c-s-d.

**Comment by realChytraeus** [comment]
I built c-s-d without any issues.

**Comment by willysr** [comment]
so is this issue solved for now?

**Comment by realChytraeus** [comment]
Issue is resolved.
