### ISSUE TITLE
Power Settings and Power Management do not work

### ISSUE THREAD

**Issue by realChytraeus** [CinnamonSlackBuilds/csb#33]
### Slackware Version
Slackware64-Current
### Cinnamon Version
4.0.2
### GIT Branch
Master
### Description
This may not apply because I have removed xfce and kde by running slackpkg remove xfce && slackpkg remove kde. IOTW, I do not have a full install of Slackware. 
That being said, the Power Settings button and the Power Management icon in the Settings panel, do nothing when I click on them. I have applied the latest updates from Slackware64-Current, 22 Nov. 2018. I am currently recompiling everything in the csb directory using build_cinnamon.sh to see if that remedies the issue.

**Comment by willysr** [comment]
Hi @realChytraeus 

I checked my VM and it's still working fine there
