### ISSUE TITLE
lxml & beautifulsoup no longer dependencies

### ISSUE THREAD

**Issue by skaendo** [CinnamonSlackBuilds/csb#34]
### Slackware Version
-current
### Cinnamon Version
3.6.7+
### GIT Branch
master
### Description
I believe that lxml and beautifulsoup are no longer required as dependencies. To confirm, I found this here: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/cinnamon&id=7f9190f91e6c7689d1e8abca0d8b1be06158a020

And the Adwaita theme fix can also be removed from the cinnamon.SlackBuild.

**Comment by willysr** [comment]
According to this (https://github.com/linuxmint/Cinnamon/blob/master/debian/control), it's still needed

**Comment by willysr** [comment]
Adwaita theme fix is applied though

**Comment by skaendo** [comment]
> According to this (https://github.com/linuxmint/Cinnamon/blob/master/debian/control), beautifulsoup is still needed

I don't see beautifulsoup or lxml in there anywhere. All I see is libsoup and its gobject gir1.2-soup.

**Comment by willysr** [comment]
libsoup = beautifulsoup :)

**Comment by skaendo** [comment]
libsoup is included in Slackware /l

beautifulsoup4 is a python package and does not use gobject.
