### ISSUE TITLE
Thunar bug with Nemo

### ISSUE THREAD

**Issue by xexpanderx** [CinnamonSlackBuilds/csb#37]
The exact same problem can be found here: https://bbs.archlinux.org/viewtopic.php?id=243728

Thunar cannot be launched anymore because thunar and nemo is fighting about who gets to be org.freedesktop.FileManager1.

I think it is a Thunar-specific bug, but I open this as an issue because it correlates with Cinnamon.

**Comment by willysr** [comment]
It has been fixed in Thunar 1.8.4
just need to wait until it hit -current
