### ISSUE TITLE
Power management isn't working

### ISSUE THREAD

**Issue by Claconcius** [CinnamonSlackBuilds/csb#42]

**Comment by willysr** [comment]
Is this on laptop?

**Comment by Claconcius** [comment]
Yes it is.

**Comment by montagdude** [comment]
It needs a newer upower and some patches (now accepted upstream) to work properly with a battery. You can check out my repo if you are interested (please see the README.md):
https://github.com/montagdude/CinnamonSlackBuilds-extended

**Comment by willysr** [comment]
I tried to maintain the same rule of not overwriting Slackware core packages.

**Comment by willysr** [comment]
try the new Cinnamon 4.2 i just uploaded.

**Comment by Claconcius** [comment]
Thanks! Not on slack anymore, but if Debian and Centos don't work out, I'll
be back.

**Comment by willysr** [comment]
@Claconcius @montagdude is this resolved now? newer UPower has been merged into current and power management should work out of the box now

**Comment by montagdude** [comment]
@willysr, Sorry, I'm not using csb anymore, so I can't check.

**Comment by Claconcius** [comment]
I don't know.
