### ISSUE TITLE
Cinnamon not loading in Current

### ISSUE THREAD

**Issue by nater1983** [CinnamonSlackBuilds/csb#54]
### Slackware Version
Slackware Current
### Cinnamon Version
5.4.11
### Description
Cinnamon DE would need to be recompiled due to not finding libffi.so.7 in Current. The Current version of libffi is 3.4.4 which is libffi.so.8

**Comment by willysr** [comment]
a rebuilt of cjs has been pushed just now, it should solve this issue.
thanks for reporting :)

please close this issue once you confirmed it

**Comment by nater1983** [comment]
Worked thank you.
