### ISSUE TITLE
Slackware64-Current user, cannot build cinnamon-settings-daemon.

### ISSUE THREAD

**Issue by chazbroam** [CinnamonSlackBuilds/csb#57]
### Slackware Version
Slackware64-Current

### Cinnamon Version
Latest

### GIT Branch
Master

### Description
Using ./build-cinnamon.sh.

GCC version 14.1.0/Meson fails building at cinnamon-settings-daemon.
CLANG/Meson fails building at pangox-compat.

**Comment by willysr** [comment]
Have you pulled from latest master branch?
i have it fixed already via 01d7a8ee5787f614a979e13728abe988ac349c1f

**Comment by willysr** [comment]
pangox-compat has been fixed by 01d7a8ee5787f614a979e13728abe988ac349c1f

**Comment by willysr** [comment]
Fixed with 8f33d1f

**Comment by chazbroam** [comment]
Many THANKS, @willysr.
