### ISSUE TITLE
Slackware64-Current fails building at muffin (subcommand).

### ISSUE THREAD

**Issue by chazbroam** [CinnamonSlackBuilds/csb#58]
### Slackware Version
Slackware64-Current

### Cinnamon Version
Latest/Master

### GIT Branch
Master

### Description
Using build-cinnamon.sh...

GCC version 14.1.0/meson/ninja Build fails at subcommand of muffin.

Thank you in advance, Willysr.

**Comment by willysr** [comment]
it works here
can you paste your error message?

**Comment by chazbroam** [comment]
`../src/core/prefs.c:2261:32: error: passing argument 1 of ‘g_strdupv’ from incompatible pointer type [-Wincompatible-pointer-types]
 2261 |           strokes = g_strdupv (bindings);
      |                                ^~~~~~~~
      |                                |
      |                                const gchar ** {aka const char **}
In file included from /usr/include/glib-2.0/glib/gstring.h:37,
                 from /usr/include/glib-2.0/glib/giochannel.h:36,
                 from /usr/include/glib-2.0/glib.h:56,
                 from ../src/core/prefs.c:31:
/usr/include/glib-2.0/glib/gstrfuncs.h:381:55: note: expected ‘gchar **’ {aka ‘char **’} but argument is of type ‘const gchar **’ {aka ‘const char **’}
  381 | gchar**               g_strdupv        (gchar       **str_array);
      |                                         ~~~~~~~~~~~~~~^~~~~~~~~
[439/711] Compiling C object src/libmuffin.so.0.0.0.p/core_workspace.c.o
../src/core/workspace.c: In function ‘copy_strut’:
../src/core/workspace.c:791:3: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
  791 |   return g_memdup(original, sizeof(MetaStrut));
      |   ^~~~~~
In file included from /usr/include/glib-2.0/glib/gstring.h:37,
                 from /usr/include/glib-2.0/glib/giochannel.h:36,
                 from /usr/include/glib-2.0/glib.h:56,
                 from /usr/include/glib-2.0/gobject/gbinding.h:30,
                 from /usr/include/glib-2.0/glib-object.h:24,
                 from ../src/meta/boxes.h:25,
                 from ../src/meta/workspace.h:25,
                 from ../src/core/workspace.c:36:
/usr/include/glib-2.0/glib/gstrfuncs.h:350:23: note: declared here
  350 | gpointer              g_memdup         (gconstpointer mem,
      |                       ^~~~~~~~
[442/711] Compiling C object src/libmuffin.so.0.0.0.p/core_window.c.o
ninja: build stopped: subcommand failed.`

Does this help?

**Comment by willysr** [comment]
are you using stable or current?

**Comment by chazbroam** [comment]
retrying building again after latest update... will report if issue continues.

**Comment by chazbroam** [comment]
`[449/711] Compiling C object src/libmuffin.so.0.0.0.p/x11_meta-selection-source-x11.c.o`

issue persists.

**Comment by willysr** [comment]
hm strange
i tested this on a clean VM without any other third party packages

**Comment by willysr** [comment]
i can't reproduce this on a clean VM, sorry
