### ISSUE TITLE
slack-required list needed

### ISSUE THREAD

**Issue by Geyup** [CinnamonSlackBuilds/csb#8]
Many users like myself, might of done expert installs of Slack and only run a small WM like Openbox as example.

So as a lightweight slackware user, I am now on my 3rd compile, as it craps on me for the things I didn't install need.

Over one hour and counting just to figure out what's needed, so it would really be nice for those of us who've done light weight installs of Slack to have some type of list to go by, as a ```slack-required```

So far at try number 3 I have come to realize these 3 things needed;

pulse
sane
libieee1284

Hmm I don't have cups installed, wonder if it's going to be try number 4 soon... LOL

THANKS

**Comment by Geyup** [comment]
Try number 4 failed, list of things needed has changed;

pulse
sane
libieee1284
libgphoto2

If this keeps failing, and I still need more I will keep updating this list.

Oh I hope this is it, or soon!

**Comment by willysr** [comment]
By default we only support full installation of Slackware, otherwise there will be many customized system out there and we simply don't have time to track and support all of them.
