### ISSUE TITLE
No VPN Plugins?

### ISSUE THREAD

**Issue by Geyup** [CinnamonSlackBuilds/csb#9]
Hello,

I'm running Slackware 14.2 x86_64

Network Settings > Add > VPN

When I click VPN I get a popup window;

Could not load VPN Plugins
Error opening directory '/etc/NetworkManager/VPN': No such file or directory

I've personally only used wicd in Slackware, and only played a very little with the NetworkManager in Slack, but I assumed this would have VPN support for it?

**Comment by willysr** [comment]
OpenVPN plugin for NetworkManager is not included in Slackware.
you may need to install them first before you can add VPN connection

**Comment by willysr** [comment]
You can install them from SBo: [](https://slackbuilds.org/repository/14.2/network/NetworkManager-openvpn/)

**Comment by Geyup** [comment]
Not using Cinnamon anymore, to unstable, it's not even stable in Mint...
